POST http://localhost:8000/customer/api/v1/customers
Content-Type: application/json

{
  "username": "hyuk",
  "email": "hyuk@ooo.com"
}

### JWT 적용 회원가입
POST http://localhost:8000/auth/api/register
Content-Type: application/json

{
    "name": "hyuk",
    "email": "hyuk@ooo.com",
    "password": "123"
}

### JWT 토큰 생성(로그인)
POST http://localhost:8000/auth/api/login
Content-Type: application/json

{
  "email": "hyuk@ooo.com",
  "password": "123"
}

### JWT 유저 정보 반환
GET http://localhost:8000/auth/api/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVrQG9vby5jb20iLCJpYXQiOjE2OTE2NDE1OTIsImV4cCI6MTY5MTY0MzM5Mn0.SJ4TzlLW5Y-o1NK7uJXmaxbZY5tjo_iBseTkobo3BBc

### 쿠폰 발급
POST http://localhost:8000/coupon/api/v1/coupon/issue
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVrQG9vby5jb20iLCJpYXQiOjE2OTE2NDE1OTIsImV4cCI6MTY5MTY0MzM5Mn0.SJ4TzlLW5Y-o1NK7uJXmaxbZY5tjo_iBseTkobo3BBc