POST http://localhost:8000/customer/api/v1/customers
Content-Type: application/json

{
  "username": "hyuk",
  "email": "hyuk@ooo.com"
}

### JWT 적용 회원가입
POST http://localhost:8000/auth/api/register
Content-Type: application/json

{
    "name": "hyuk",
    "email": "hyuk@ooo.com",
    "password": "123"
}

### JWT 토큰 생성(로그인)
POST http://localhost:8000/auth/api/login
Content-Type: application/json

{
  "email": "hyuk@ooo.com",
  "password": "123"
}

### JWT 토큰 검증
GET http://localhost:8000/auth/api/validate?token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeXVrQG9vby5jb20iLCJpYXQiOjE2OTE0OTA0NzcsImV4cCI6MTY5MTQ5MjI3N30.gDnbBijrIDmAHNzoX3CoP08xhjHEjaAfn1LaLV__qSA
Content-Type: application/json